server:
  port: 8082
  servlet:
    context-path: /identity
spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/bookteria_identity"
    driverClassName: "org.postgresql.Driver"
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgresql
jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    profile: http://localhost:8081/profile
      