server:
  port: 8888

app:
  api-prefix: /api/v1
  strip-prefix: 2
spring:
  application:
    name: api-gateway
  cloud: 
    gateway:
      globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "http://localhost:3000"  # Explicitly allow your frontend origin
              allowedHeaders: "*"  # Allow all headers (adjust as necessary for security)
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
              allowCredentials: true  # Include credentials like cookies if needed
      routes:
        - id: identity_service
          uri: 'http://localhost:8082'
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=${app.strip-prefix}
        - id: profile_service
          uri: 'http://localhost:8081'
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=${app.strip-prefix}
        - id: blog_service
          uri: 'http://localhost:5000'
          predicates:
            - Path=${app.api-prefix}/blog/**
          filters:
            - StripPrefix=${app.strip-prefix}